name: news_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.6
  auto_route: ^8.1.3
  flutter_bloc: ^8.1.5
  dio: ^5.4.3+1
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  retrofit: ^4.1.0
  
dev_dependencies:
  retrofit_generator: '>=7.0.0 <8.0.0'
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
 
  build_runner: ^2.1.0
  
  

  flutter_native_splash: ^1.2.0

flutter_native_splash:
  image: assets/icons/space3.png
  color: "#FFFFFF"

flutter:

  uses-material-design: true

  assets:
   - assets/icons/